# Generated by Django 2.1.4 on 2019-01-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20190109_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='line_item_total',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=100),
            preserve_default=False,
        ),
    ]
