# Generated by Django 2.1.4 on 2019-01-09 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_cart_sub_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='upadted',
            new_name='updated',
        ),
    ]
